version: '3.8'
services:

  db:
    image: postgres:15
    container_name: postgres_productos
    environment:
      POSTGRES_DB: productosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: api_productos
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/productosdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_JWT_SECRET: bulbasaureselmejorinicialynolopiensodiscutirconnadie
      SPRING_SECURITY_JWT_EXPIRATION_MS: 3600000
    ports:
      - "8080:8080"

volumes:
  pgdata:
