name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Cache del repositorio Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Compilar y testear
        run: mvn clean verify

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y tag de la imagen
        run: |
          IMAGE=baravenp/gestion-productos
          TAG=${GITHUB_SHA::8}
          docker build -t $IMAGE:latest -t $IMAGE:$TAG .

      - name: Push de la imagen
        run: |
          IMAGE=baravenp/gestion-productos
          TAG=${GITHUB_SHA::8}
          docker push $IMAGE:latest
          docker push $IMAGE:$TAG
